---
listen_addr: 127.0.0.1
listen_port: 6901
db_url: sqlite:///srv/airtifex/data.db
#db_url: postgres://airtifex:airtifex@localhost/airtifex
jwt_secret: change-me!

llms:
  # - model_path: /srv/airtifex/llm_models/ggml-alpaca-7b-q4.bin
  #   model_description: Alpaca 7B, quantized
  #   float16: false

stable_diffusion:
  #- version: v2.1
    #model_description: Stable Diffusion v2.1
    #clip_weights_path: ./sd_models/clip_v2.1.ot
    #vae_weights_path: ./sd_models/vae_v2.1.ot
    #unet_weights_path: ./sd_models/unet_v2.1.ot
    #vocab_file: ./sd_models/bpe_simple_vocab_16e6.txt

  #- version: v1.5
    #model_description: Stable Diffusion v1.5
    #clip_weights_path: ./sd_models/clip_v1.5.ot
    #vae_weights_path: ./sd_models/vae_v1.5.ot
    #unet_weights_path: ./sd_models/unet_v1.5.ot
    #vocab_file: ./sd_models/bpe_simple_vocab_16e6.txt
